services:
  - type: web
    name: kitob-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    autoDeploy: false
    pythonversion: "3.11"
